require_relative 'bot_views/base'
require_relative 'bot_views/uvi/entry_point'
require_relative 'bot_views/uvi/action'
require_relative 'bot_views/suntime/entry_point'
require_relative 'bot_views/suntime/midpoint'
require_relative 'bot_views/suntime/submit'